# fly.toml app configuration file for intent-engine
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'intent-engine'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
