### Intent Engine API - Swap Endpoints
### Base URL: http://localhost:3002

##########################
### Swap Quote Endpoints ###
##########################

### Get best swap quote - USDC to ETH on Ethereum
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&fromTokenDecimals=6&toTokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&toTokenDecimals=18&amount=1000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=1&to_token_price=3000&eth_price=3000

###

### Get swap quote - USDT to USDC on Ethereum
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xdAC17F958D2ee523a2206206994597C13D831ec7&fromTokenDecimals=6&toTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&toTokenDecimals=6&amount=1000000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=0.5&to_token_price=1&eth_price=3000

###

### Get swap quote - WETH to USDC on Arbitrum  
GET {{baseUrl}}/swap/quote?chainId=42161&fromTokenAddress=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1&fromTokenDecimals=18&toTokenAddress=0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8&toTokenDecimals=6&amount=1000000000000000000&fromAddress=0x742d35Cc6A5C7b8E9dC85c70D8c15516e8b3eEeF&slippage=1&to_token_price=1&eth_price=3000

###

### Get swap quote - USDC to WETH on Base
GET {{baseUrl}}/swap/quote?chainId=8453&fromTokenAddress=0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913&fromTokenDecimals=6&toTokenAddress=0x4200000000000000000000000000000000000006&toTokenDecimals=18&amount=3000000000&fromAddress=0x742d35Cc6A5C7b8E9dC85c70D8c15516e8b3eEeF&slippage=1&to_token_price=3000&eth_price=3000

###

### Get supported DEX providers
GET {{baseUrl}}/swap/providers
Content-Type: application/json

###

##########################
### Error Cases ###
##########################

### Invalid chain ID
GET {{baseUrl}}/swap/quote?chainId=999&fromTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&fromTokenDecimals=6&toTokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&toTokenDecimals=18&amount=1000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=1&to_token_price=3000&eth_price=3000

###

### Invalid token address
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xinvalid&fromTokenDecimals=6&toTokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&toTokenDecimals=18&amount=1000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=1&to_token_price=3000&eth_price=3000

###

### Missing required parameters
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&fromTokenDecimals=6

###

### Excessive slippage
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&fromTokenDecimals=6&toTokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&toTokenDecimals=18&amount=1000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=50&to_token_price=3000&eth_price=3000

###

##########################
### Variables ###
##########################

@baseUrl = http://localhost:3002

##########################
### Common Tokens by Chain ###
##########################

### Ethereum Mainnet (chainId: 1)
# ETH: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
# USDC: 0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2
# USDT: 0xdAC17F958D2ee523a2206206994597C13D831ec7
# WETH: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2
# DAI: 0x6B175474E89094C44Da98b954EedeAC495271d0F

### Arbitrum (chainId: 42161)
# ETH: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
# WETH: 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1
# USDC: 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
# USDT: 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
# ARB: 0x912CE59144191C1204E64559FE8253a0e49E6548

### Base (chainId: 8453)
# ETH: 0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
# WETH: 0x4200000000000000000000000000000000000006
# USDC: 0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913
# cbETH: 0x2Ae3F1Ec7F1F5012CFEab0185bfc7aa3cf0DEc22

##########################
### High Volume Swaps ###
##########################

### Large USDC to ETH swap
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&fromTokenDecimals=6&toTokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&toTokenDecimals=18&amount=100000000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=1&to_token_price=3000&eth_price=3000

###

### Small amount swap (dust level)
GET {{baseUrl}}/swap/quote?chainId=1&fromTokenAddress=0xA0b86a33E6441c8e4B23b4bcBd3e5ccB30B4c1b2&fromTokenDecimals=6&toTokenAddress=0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee&toTokenDecimals=18&amount=1000000&fromAddress=0x2eCBC6f229feD06044CDb0dD772437a30190CD50&slippage=1&to_token_price=3000&eth_price=3000

###